### ISSUE TITLE
Dynamics used numbers at maturity for reproduction instead of numbers at first parturition

### ISSUE THREAD

**Issue by grantdadams** [mcsiple/mmrefpoints#49]
The following statements in the `dynamics` function suggests that the number of recruits in a year is a function of the number of mature individuals in that year because the N matrix includes age-0s, right? 
`
Nrep[Yr + 1] <- sum(N[Yr + 1, AgePart:(nages + 1)])      `
`N[Yr + 1, 1] <- Nrep[Yr + 1] * (f0 + (fmax - f0) * (1 - (Tot1P[Yr + 1] / K1plus)^z)) # rec
`

Should it rather be the number of individuals giving birth in that year (age-at-first parturition)?
`
Nrep[Yr + 1] <- sum(N[Yr + 1, (AgePart+1):(nages + 1)])   `
`   
N[Yr + 1, 1] <- Nrep[Yr + 1] * (f0 + (fmax - f0) * (1 - (Tot1P[Yr + 1] / K1plus)^z)) # rec
`

**Comment by mcsiple** [comment]
I think you're right, Grant. I remember changing this a bunch because it used to be age at maturity instead of age at parturition and I think we overstepped the indexing. I'm changing it to your suggestion for now and double checking with André just to make sure there isn't something more complicated going on. Thank you! fixed w commit 5193bea0 .
